name: Add new issues to project

on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: Add issue to project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/projects/columns/${{ secrets.PROJECT_COLUMN_ID }}/cards \
          --header 'Authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.inertia-preview+json' \
          --header 'Content-Type: application/json' \
          --data '{"content_id": ${{ github.event.issue.id }},"content_type": "Issue"}'
