name: Assign custom field to new issues

on:
  issues:
    types: [opened]

jobs:
  assign_custom_field:
    runs-on: ubuntu-latest
    steps:
    - name: Assign custom field
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl --request POST \
          --url https://api.github.com/graphql \
          --header 'Authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{"query":"mutation { updateIssue(input: { id: \"${{ github.event.issue.node_id }}\", fieldId: \"カスタムフィールドID\", fieldValue: \"選択肢のID\" }) { issue { title } } }"}'
