name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        run: |
          curl --request POST \
          --url https://api.github.com/projects/PROJECT_ID/cards \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data '{"content_id": ${{ github.event.issue.id }},"content_type": "Issue"}'
