name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_URL: https://api.github.com/orgs/Escher-js/projects/1
        run: |
          curl --request POST \
          --url $PROJECT_URL/cards \
          --header "Authorization: Bearer $GITHUB_TOKEN" \
          --header "Content-Type: application/json" \
          --data '{"content_id": ${{ github.event.issue.id }},"content_type": "Issue"}'
